# permissions for end users to view appreleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: apprelease-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: apimachinery
    app.kubernetes.io/part-of: apimachinery
    app.kubernetes.io/managed-by: kustomize
  name: apprelease-viewer-role
rules:
- apiGroups:
  - drivers.x-helm.dev
  resources:
  - appreleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - drivers.x-helm.dev
  resources:
  - appreleases/status
  verbs:
  - get
