# permissions for end users to edit products.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: product-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: apimachinery
    app.kubernetes.io/part-of: apimachinery
    app.kubernetes.io/managed-by: kustomize
  name: product-editor-role
rules:
- apiGroups:
  - products.x-helm.dev
  resources:
  - products
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - products.x-helm.dev
  resources:
  - products/status
  verbs:
  - get
