# permissions for end users to view orders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: order-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: apimachinery
    app.kubernetes.io/part-of: apimachinery
    app.kubernetes.io/managed-by: kustomize
  name: order-viewer-role
rules:
- apiGroups:
  - releases.x-helm.dev
  resources:
  - orders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - releases.x-helm.dev
  resources:
  - orders/status
  verbs:
  - get
