# permissions for end users to edit bundles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bundle-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: apimachinery
    app.kubernetes.io/part-of: apimachinery
    app.kubernetes.io/managed-by: kustomize
  name: bundle-editor-role
rules:
- apiGroups:
  - releases.x-helm.dev
  resources:
  - bundles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - releases.x-helm.dev
  resources:
  - bundles/status
  verbs:
  - get
