apiVersion: charts.x-helm.dev/v1alpha1
kind: ClusterChartPreset
metadata:
  labels:
    app.kubernetes.io/name: clusterchartpreset
    app.kubernetes.io/instance: clusterchartpreset-sample
    app.kubernetes.io/part-of: apimachinery
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: apimachinery
  name: clusterchartpreset-sample
spec:
  # TODO(user): Add fields here
